language: php

sudo: false

php:
  - 7.2

env:
  - LARAVEL=5.8.*
  - LARAVEL=5.7.*
  - LARAVEL=5.6.*
  - LARAVEL=5.5.*

matrix:
  fast_finish: true

before_install:
  - composer require "laravel/framework:${LARAVEL}" --update-with-all-dependencies

before_script:
  - travis_retry composer install --prefer-source --no-interaction
  - composer update

scripts:
  - phpunit -c phpunit.xml

notifications:
  email: false
