language: php

sudo: false

php:
  - 7.2

env:
  - VERSION=58
  - VERSION=57
  - VERSION=56
  - VERSION=55

matrix:
  fast_finish: true


before_script:
  #- travis_retry composer self-update
  #- travis_retry composer install --prefer-source --no-interaction
  - pwd
  - chmod +x tests/scripts/*.sh

after_success:
  - travis_retry php vendor/bin/php-coveralls

scripts:
  - ./tests/scripts/${VERSION}.sh

notifications:
  email: false
